from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vertodaslasubicaciones/', views.VerTodasLasUbicaciones),
    path('crearubicacion/', views.CrearUbicacion),
    path('cambiarubicacion/<int:pk>/', views.CambiarUbicacion),
    path('vertodoslosbeneficiarios/', views.VerTodosLosBeneficiarios),
    path('crearbeneficiario/', views.CrearBeneficiario),
    path('cambiarbeneficiario/<int:pk>/', views.CambiarBeneficiario),
    path('vertodoslosproyectos/', views.VerTodosLosProyectos),
    path('crearproyecto/', views.CrearProyecto),
    path('cambiarproyecto/<int:pk>/', views.CambiarProyecto),
    path('vertodaslaspersonas/', views.VerTodasLasPersonas),
    path('crearpersona/', views.CrearPersona),
    path('cambiarpersona/<int:pk>/', views.CambiarPersona),
    path('vertodoslosmiembros/', views.VerTodosLosMiembros),
    path('crearmiembro/', views.CrearMiembro),
    path('cambiarmiembro/<int:pk>/', views.CambiarMiembro),
    path('vertodosloscolaboradores/', views.VerTodosLosColaboradores),
    path('crearcolaborador/', views.CrearColaborador),
    path('cambiarcolaborador/<int:pk>/', views.CambiarColaborador),
    path('vertodoslosusuarios/', views.VerTodosLosUsuarios),
    path('crearusuario/', views.CrearUsuario),
    path('cambiarusuario/<int:pk>/', views.CambiarUsuario),
    path('vertodoslosconsorcios/', views.VerTodosLosConsorcios),
    path('crearconsorcio/', views.CrearConsorcio),
    path('cambiarconsorcio/<int:pk>/', views.CambiarConsorcio),
    path('vertodoslosfinanciadores/', views.VerTodosLosFinanciadores),
    path('crearfinanciador/', views.CrearFinanciador),
    path('cambiarfinanciador/<int:pk>/', views.CambiarFinanciador),
    path('vertodoslosinstrumentos/', views.VerTodosLosInstrumentos),
    path('crearinstrumento/', views.CrearInstrumento),
    path('cambiarinstrumento/<int:pk>/', views.CambiarInstrumento),
    path('vertodaslaspostulaciones/', views.VerTodasLasPostulaciones),
    path('crearpostulacion/', views.CrearPostulacion),
    path('cambiarpostulacion/<int:pk>/', views.CambiarPostulacion),
]