from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verubicacions/', views.VerUbicacions),
    path('crearubicacion/', views.CrearUbicacion),
    path('modificarubicacion/', views.ModificarUbicacion),
    path('verpersonas/', views.VerPersonas),
    path('crearpersona/', views.CrearPersona),
    path('modificarpersona/', views.ModificarPersona),
    path('vermiembrodeunaempresas/', views.VerMiembroDeUnaEmpresas),
    path('crearmiembrodeunaempresa/', views.CrearMiembroDeUnaEmpresa),
    path('modificarmiembrodeunaempresa/', views.ModificarMiembroDeUnaEmpresa),
    path('vermiembrodeproyectos/', views.VerMiembroDeProyectos),
    path('crearmiembrodeproyecto/', views.CrearMiembroDeProyecto),
    path('modificarmiembrodeproyecto/', views.ModificarMiembroDeProyecto),
    path('verusuariodematchafundings/', views.VerUsuarioDeMatchaFundings),
    path('crearusuariodematchafunding/', views.CrearUsuarioDeMatchaFunding),
    path('modificarusuariodematchafunding/', views.ModificarUsuarioDeMatchaFunding),
    path('verbeneficiarios/', views.VerBeneficiarios),
    path('crearbeneficiario/', views.CrearBeneficiario),
    path('modificarbeneficiario/', views.ModificarBeneficiario),
    path('verconsorciodebeneficiarioss/', views.VerConsorcioDeBeneficiarioss),
    path('crearconsorciodebeneficiarios/', views.CrearConsorcioDeBeneficiarios),
    path('modificarconsorciodebeneficiarios/', views.ModificarConsorcioDeBeneficiarios),
    path('verproyectos/', views.VerProyectos),
    path('crearproyecto/', views.CrearProyecto),
    path('modificarproyecto/', views.ModificarProyecto),
    path('verfinanciadors/', views.VerFinanciadors),
    path('crearfinanciador/', views.CrearFinanciador),
    path('modificarfinanciador/', views.ModificarFinanciador),
    path('verinstrumentos/', views.VerInstrumentos),
    path('crearinstrumento/', views.CrearInstrumento),
    path('modificarinstrumento/', views.ModificarInstrumento),
    path('verpostulacions/', views.VerPostulacions),
    path('crearpostulacion/', views.CrearPostulacion),
    path('modificarpostulacion/', views.ModificarPostulacion),
]